// Given two strings s and t which consist of only lowercase letters.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Find the letter that was added in t.
//
// Example:
//
// Input:
// s = "abcd"
// t = "abcde"
//
// Output:
// e
//
// Explanation:
// 'e' is the letter that was added.
class Solution {
public:
    char findTheDifference(string s, string t) {
        map<char, int> smap;
        for (auto c: s) smap[c]++;

        for (auto c: t) {
            smap[c]--;
            if (smap[c] == 0) smap.erase(c);
        }

        return smap.begin()->first;
    }
};
